# builder
FROM node:18-alpine AS builder

ARG BUILD_ARG_NEXT_PUBLIC_BASE_URL
ARG BUILD_ARG_NEXT_PUBLIC_KAKAO_INTERGRITY
ARG BUILD_ARG_NEXT_PUBLIC_KAKAO_JS_KEY
ARG BUILD_ARG_NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG BUILD_ARG_NEXT_PUBLIC_SUPABASE_URL

ENV NEXT_PUBLIC_BASE_URL=$BUILD_ARG_NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_KAKAO_INTERGRITY=$BUILD_ARG_NEXT_PUBLIC_KAKAO_INTERGRITY
ENV NEXT_PUBLIC_KAKAO_JS_KEY=$BUILD_ARG_NEXT_PUBLIC_KAKAO_JS_KEY
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$BUILD_ARG_NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$BUILD_ARG_NEXT_PUBLIC_SUPABASE_URL

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

RUN rm -rf .next
RUN npm run build

# runner
FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
CMD ["node", "server.js"]