# 1. Node.js 경량 이미지
FROM node:18-alpine

# 2. 작업 디렉토리 생성
WORKDIR /app

# 3. 종속성 설치
COPY package.json package-lock.json* ./
RUN npm install

ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_KAKAO_INTERGRITY
ARG NEXT_PUBLIC_KAKAO_JS_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY

ARG KAKAO_CLIENT_ID
ARG KAKAO_REDIRECT_URI
ARG KAKAO_SECRET_KEY
ARG BASE_URL
ARG JWT_ACCESS_SECRET
ARG JWT_REFRESH_SECRET
ARG SUPABASE_URL
ARG SUPABASE_SERVICE_ROLE_KEY

ENV NEXT_PUBLIC_BASE_URL = $NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_KAKAO_INTERGRITY = $NEXT_PUBLIC_KAKAO_INTERGRITY
ENV NEXT_PUBLIC_KAKAO_JS_KEY = $NEXT_PUBLIC_KAKAO_JS_KEY
ENV NEXT_PUBLIC_SUPABASE_URL = $NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY = $NEXT_PUBLIC_SUPABASE_ANON_KEY

ENV KAKAO_CLIENT_ID = $KAKAO_CLIENT_ID
ENV KAKAO_REDIRECT_URI = $KAKAO_REDIRECT_URI
ENV KAKAO_SECRET_KEY = $KAKAO_SECRET_KEY
ENV BASE_URL = $BASE_URL
ENV JWT_ACCESS_SECRET = $JWT_ACCESS_SECRET
ENV JWT_REFRESH_SECRET = $JWT_REFRESH_SECRET
ENV SUPABASE_URL = $SUPABASE_URL
ENV SUPABASE_SERVICE_ROLE_KEY = $SUPABASE_SERVICE_ROLE_KEY


# 4. Next.js 코드 복사
COPY . .

# 5. Next.js 빌드
RUN npm run build

# 6. 포트 열기
EXPOSE 3000

# 7. 앱 실행
CMD ["npm", "run", "dev"]