version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hab
    environment:
      - NODE_ENV=production
    env_file:
      - app.env
    expose:
      - "3000"
    volumes:
      - next-static:/app/.next/static
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/hab.jeongyongseong.kr/fullchain.pem:/etc/letsencrypt/live/hab.jeongyongseong.kr/fullchain.pem:ro
      - /etc/letsencrypt/live/hab.jeongyongseong.kr/privkey.pem:/etc/letsencrypt/live/hab.jeongyongseong.kr/privkey.pem:ro
      - next-static:/app/.next/static:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

volumes:
  next-static:

networks:
  app-network:
    driver: bridge
