name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }} # GitHub Secrets에서 SSH 개인 키 가져오기

      - name: Deploy to EC2 instance
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_KAKAO_INTERGRITY: ${{ secrets.NEXT_PUBLIC_KAKAO_INTERGRITY }}
          NEXT_PUBLIC_KAKAO_JS_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_JS_KEY }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}

          BASE_URL: ${{ secrets.BASE_URL }}
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
          KAKAO_SECRET_KEY: ${{ secrets.KAKAO_SECRET_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

        run: |
          echo "Setting up SSH known_hosts"
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ env.EC2_HOST }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts # 권한 문제 방지


          echo "Executing deployment script on EC2..." 
          ssh -T ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }} << 'EOF'
            set -e

            echo "Connected to EC2 instance: ${{ env.EC2_HOST }}"
            
            cd ~/hab 
            
            echo "Pulling latest code from Git..."
            git pull origin main
            
            echo "Creating/Updating .env file for runtime..."
            echo "${{ env.ENV_FILE_CONTENT }}" > app.env 
            echo "BASE_URL=${{ env.BASE_URL }}" >> app.env
            echo "JWT_ACCESS_SECRET=${{ env.JWT_ACCESS_SECRET }}" >> app.env
            echo "JWT_REFRESH_SECRET=${{ env.JWT_REFRESH_SECRET }}" >> app.env
            echo "KAKAO_CLIENT_ID=${{ env.KAKAO_CLIENT_ID }}" >> app.env
            echo "KAKAO_REDIRECT_URI=${{ env.KAKAO_REDIRECT_URI }}" >> app.env
            echo "KAKAO_SECRET_KEY=${{ env.KAKAO_SECRET_KEY }}" >> app.env
            echo "SUPABASE_SERVICE_ROLE_KEY=${{ env.SUPABASE_SERVICE_ROLE_KEY }}" >> app.env
            echo "SUPABASE_URL=${{ env.SUPABASE_URL }}" >> app.env
            
            echo "Building Docker images (web service specifically)..."

            sudo docker compose build --no-cache \
              --build-arg BUILD_ARG_NEXT_PUBLIC_BASE_URL="${{env.NEXT_PUBLIC_BASE_URL}}" \
              --build-arg BUILD_ARG_NEXT_PUBLIC_KAKAO_INTERGRITY="${{env.NEXT_PUBLIC_KAKAO_INTERGRITY}}" \
              --build-arg BUILD_ARG_NEXT_PUBLIC_KAKAO_JS_KEY="${{env.NEXT_PUBLIC_KAKAO_JS_KEY}}" \
              --build-arg BUILD_ARG_NEXT_PUBLIC_SUPABASE_ANON_KEY="${{env.NEXT_PUBLIC_SUPABASE_ANON_KEY}}" \
              --build-arg BUILD_ARG_NEXT_PUBLIC_SUPABASE_URL="${{env.NEXT_PUBLIC_SUPABASE_URL}}" \
            web
            
            echo "Stopping and recreating services..."
            sudo docker compose down -v
            sudo docker compose up -d
            
            echo "Cleaning up old Docker images (optional)..."
            sudo docker image prune -af
            
            echo "Deployment to EC2 complete!"
          EOF
